//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystemApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRegister
    {
        public int ID { get; set; }
        public string School { get; set; }
        public string Class { get; set; }
        public string Subject { get; set; }
        public string SchoolStaff { get; set; }
        public string Student { get; set; }
        public Nullable<System.DateTime> ClockIn { get; set; }
        public Nullable<System.DateTime> ClockOut { get; set; }
        public Nullable<System.DateTime> LunchStart { get; set; }
        public Nullable<System.DateTime> LunchEnd { get; set; }
        public bool Present { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
