//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystemApi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolSystemEntities : DbContext
    {
        public SchoolSystemEntities()
            : base("name=SchoolSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentType> AssessmentTypes { get; set; }
        public virtual DbSet<AttendanceRegister> AttendanceRegisters { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassesAndGrade> ClassesAndGrades { get; set; }
        public virtual DbSet<ClassesAndSubject> ClassesAndSubjects { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<SchoolFeaturesAndFunction> SchoolFeaturesAndFunctions { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SchoolType> SchoolTypes { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<TeachersAndClass> TeachersAndClasses { get; set; }
        public virtual DbSet<TeachersAndSubject> TeachersAndSubjects { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<UserFeaturesAndFunction> UserFeaturesAndFunctions { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInSchool> UsersInSchools { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
    }
}
