//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystemApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeaturesAndFunction
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> FeatureID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
