//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystemApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public string UserID { get; set; }
        public string School_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Identification { get; set; }
        public string IdentificationType { get; set; }
        public string Nationality { get; set; }
        public string Race { get; set; }
        public Nullable<int> NumberOfKids { get; set; }
        public string HomeAddress { get; set; }
        public string AlternativeAddress { get; set; }
        public string Occupation { get; set; }
        public string AlternativeEmail { get; set; }
        public string AlternativeTelephone { get; set; }
    }
}
