//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystemApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFunction
    {
        public string UserID { get; set; }
        public string UserRole { get; set; }
        public bool CreateSchool { get; set; }
    }
}
