//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystemApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string LastPassword { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public int LoginAttempts { get; set; }
        public bool LockedOut { get; set; }
        public bool Active { get; set; }
    }
}
